### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by garfieldnate** [garfieldnate/ray_tracer_challenge#1]
[projectile PPM file](https://github.com/garfieldnate/ray_tracer_challenge/files/4173340/project.ppm.txt)
![projectile image](https://user-images.githubusercontent.com/778453/74073416-8b92bf00-4a0a-11ea-9397-7e7ed1449682.png)

**Comment by garfieldnate** [comment]
![squiished sphere's shadow in red](https://user-images.githubusercontent.com/778453/74366598-99608f80-4dd0-11ea-9ef2-53c16eaa0133.png)

[squished_sphere_shadow_red.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4194377/output.ppm.txt)

**Comment by garfieldnate** [comment]
![3d squashed sphere](https://user-images.githubusercontent.com/778453/74382948-94aad400-4dee-11ea-819b-a196cc2aac7e.png)
[output.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4195313/output.ppm.txt)

**Comment by garfieldnate** [comment]
![sphere scene](https://user-images.githubusercontent.com/778453/74574065-b63cc480-4f82-11ea-99bf-d78737465e29.png)
[output.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4207158/output.ppm.txt)

**Comment by garfieldnate** [comment]
![first scene with shadows](https://user-images.githubusercontent.com/778453/74589036-1cb4f780-5002-11ea-8aef-3f23113ae84c.png)
[output.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4208532/output.ppm.txt)

**Comment by garfieldnate** [comment]
![salt-and-pepper noise](https://user-images.githubusercontent.com/778453/74589060-584fc180-5002-11ea-8540-2d312332cbec.png)

This is what happens when you don't use an epsilon (or a big enough epsilon) in shading when you also have drop shadows.

**Comment by garfieldnate** [comment]
![First Plane](https://user-images.githubusercontent.com/778453/74609469-798bdd00-50ea-11ea-9b9d-8c04a11303ed.png)

[first_plane.ppm.txt](https://github.com/garfieldnate/ray_tracer_challenge/files/4210394/first_plane.ppm.txt)

**Comment by garfieldnate** [comment]
This is what happens when you use a world point to apply a pattern. Everything looks like it's being camouflaged!

![camouflage](https://user-images.githubusercontent.com/778453/74679251-9e04b980-51bd-11ea-91a2-8693dc11fc4f.png)

**Comment by garfieldnate** [comment]
![Patterns](https://user-images.githubusercontent.com/778453/74777781-851e0600-529a-11ea-8617-df0e659b25a8.png)

[first_patterns.ppm.txt](https://github.com/garfieldnate/ray_tracer_challenge/files/4221660/first_patterns.ppm.txt)

Sorry about the nasty colors! Also, I have a 2d sine wave on the floor but for some reason couldn't figure out how to translate it until the rings were in view.

**Comment by garfieldnate** [comment]
![reflect_refract](https://user-images.githubusercontent.com/778453/75098356-6e86f000-55b5-11ea-8830-eb89f1e076d3.png)

[reflect_refract.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4239856/reflect_refract.ppm.txt)

**Comment by garfieldnate** [comment]
Making that last one better by adding shininess to the glass sphere:
![better_reflection_refraction](https://user-images.githubusercontent.com/778453/75114159-f91e2c80-5653-11ea-9262-4ebebc19ca22.png)
[better_reflect_refract.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4241433/better_reflect_refract.ppm.txt)

I've also removed the sphere's shadow, as the shadow's refraction looked dumb and the shadow itself was not too realistic. However, now it just looks like it's floating there instead of sitting on the surface, so still not great. Really need to implement caustics, but they aren't even in the book.

**Comment by garfieldnate** [comment]
![cones and cylinders](https://user-images.githubusercontent.com/778453/75149450-4a84f500-5702-11ea-851a-b298b3ab40ce.png)
[cones_and_cylinders.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4244328/output.ppm.txt)

Now we have cones and cylinders! The reflection on the cone *really* highlights why we need anti-aliasing.

**Comment by garfieldnate** [comment]
![messy glass hexagon](https://user-images.githubusercontent.com/778453/75613180-f7100e00-5b2a-11ea-9470-01edd828b445.png)

[hexagon.ppm](https://github.com/garfieldnate/ray_tracer_challenge/files/4270750/hexagon.ppm.txt)

There are plenty of technical issues here, but I thought it looked cool ayway! 

The group functionality, which is what's actually being tested, is working correctly and the hexagon shape from the book is being constructed properly.

The three issues I see:

* Aliasing makes some pretty crazy patterns here. I kinda like them, but I want to see what happens with anti-aliasing on.
* No CSG yet, so you can see the borders between the cylinders and the spheres that make up the hexagon.
* The background is supposed to be checkered. I guess maybe I messed up the pattern? It looks cool, too, though :)

**Comment by garfieldnate** [comment]
Another one with different colors for funsies:

![color hexagon](https://user-images.githubusercontent.com/778453/75613336-a0a3cf00-5b2c-11ea-820c-916c83e990c3.png)

**Comment by garfieldnate** [comment]
An example of shadow *banding*, caused by using an exact, grid-based intensity calculation with rectangular lights:

![shadow banding](https://user-images.githubusercontent.com/778453/76151023-7f089180-60b0-11ea-9b55-0fe77717236c.png)

**Comment by garfieldnate** [comment]
And here's what the shadows look like when we do random sampling. Salt and pepper noise!

![noisy shadows](https://user-images.githubusercontent.com/778453/76170903-be091680-6186-11ea-8d46-894eb92f2292.png)

**Comment by garfieldnate** [comment]
Finally working soft shadows:
![soft shadows](https://user-images.githubusercontent.com/778453/76680715-33437400-65eb-11ea-9a32-cf4536543d43.png)


I wasn't able to do the last test from the bonus chapter because I didn't understand it. But it's working well enough to reproduce the glamor shot provided by the author.

**Comment by garfieldnate** [comment]
My first OBJ file rendering!
![dragon](https://user-images.githubusercontent.com/778453/77235500-70dd6980-6bb6-11ea-925b-b24463fe8adf.png)

I didn't render anything while going through the book because without an acceleration structure in place (BVH), I knew it would take forever to render. 

#### Render Times
I tried different 
* BVH, no dividing: 1m40s
* divide(10): 40s
* divide(7): 27s
* divide(6): 30s
* divide(5): 26s
* divide(4): 26s
* divide(3): 38s

Dividing itself takes a little while, so there is a sweet spot.

**Comment by garfieldnate** [comment]
Full dragon scene complete!

![here be dragons](https://user-images.githubusercontent.com/778453/77516571-f002c400-6e7a-11ea-8c0a-b81b2c0f82f4.png)

It's a little different from what's in the book in terms of pedestal sizes and such, but I'm fine with it.

Takes about 1m 43s to run it. A lot of the time is taken up reading the dragon OBJ file 6 times and copying material objects to each of the triangles. We're also still single threaded, and I know the BVH stuff can be improved with some kind of box occlusion.

**Comment by garfieldnate** [comment]
My first texture!

![checkered sphere](https://user-images.githubusercontent.com/778453/77580764-db571800-6edc-11ea-9444-f4b0f7b0d6ef.png)

This also shows, again, that there's something wrong with our 3d checkers implementation.

**Comment by garfieldnate** [comment]
Sphere, cylinder and cube textures working, plus image mapping!
![example textures](https://user-images.githubusercontent.com/778453/77845808-f615df00-71b1-11ea-991e-9fd916433a86.png)

**Comment by garfieldnate** [comment]
And finally, a skybox!
![image](https://user-images.githubusercontent.com/778453/77849222-56b11600-71ca-11ea-80bf-b3babf697fb4.png)

**Comment by fremag** [comment]
Thanks alot for all your pictures and code/commit comments !

**Comment by garfieldnate** [comment]
Thanks, @fremag! Your ray tracer is amazing and has definitely been an inspiration for me. I love the UI you've made and your architecture seems really clean, too. 

I've been trying to put in as much commentary as possible in mine, since it's a learning project. I'm having a blast! I don't always have great commit comments, but I hope enough that `git blame` on a puzzling line somewhere might have some helpful info.
